#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another URL with 301 status

# Update package list and install Nginx
apt-get update -y && apt-get install -y nginx

# Add redirection to the Nginx default server block
sed -i '/server {/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx without systemctl
service nginx restart
