#!/usr/bin/env bash
# Script that configures Nginx on a new Ubuntu machine with a custom HTTP response header

# Update package list and install Nginx
apt-get -y update
apt-get -y install nginx

# Add the custom header to the Nginx configuration

sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

# Restart Nginx to apply changes
service nginx restart
