#!/usr/bin/env bash
# Script that configures HAProxy in a load balancer 

set -e

# Install required packages and add HAProxy repository
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.*

# Configure HAProxy with roundrobin balancing
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT >> /etc/haproxy/haproxy.cfg

frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 806443-web-01 100.24.72.31:80 check
    server 806443-web-02 54.145.82.172:80 check
EOT

# Restart HAProxy to apply the new configuration
service haproxy restart

echo "HAProxy has been installed and configured successfully."
