#!/usr/bin/env bash
# Script that configures HAProxy in a load balancer 

# Install required packages and add HAProxy repository
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*

# Configure HAProxy with roundrobin balancing
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 806443-web-01 100.24.72.31:80 check\n\tserver 806443-web-02 54.145.82.172:80 check" >> /etc/haproxy/haproxy.cfg

# Restart HAProxy
service haproxy restart
