#!/usr/bin/env bash
# This script configures an Ubuntu server to ensure Nginx is running and listening on port 80 of all active IPv4 IPs
# Confirm Nginx is listening on port 80
sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080 default_server;/listen [::]:80 default_server;/' /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default

#Restart Nginx
systemctl restart nginx
