#!/usr/bin/env bash
# This script configures an Ubuntu server to ensure Nginx is running and listening on port 80 of all active IPv4 IPs
sudo apt-get update
sudo apt-get install -y nginx

sudo service apache2 stop

sudo mv /var/www/html/index.html /var/www/html/index.html.backup
sudo apt-get install --reinstall nginx-common
sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default
sudo sed -i "/s/sites-enabled/sites-available/" /etc/nginx/nginx.conf

sudo service nginx start
