#!/usr/bin/env bash
# This script fixes Nginx to ensure it runs and listens on port 80
sed -i 's/listen 80 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
service nginx restart
