#!/usr/bin/env bash
# This script lists the non-hidden files in the current directory displaying only the name after the first dash

for file in *; do
	if [[ "$file" == *-* ]]; then
		echo "${file#*-}"
	else
		echo "$file"
	fi
done
