#!/usr/bin/env bash
# This script listens on port 98 on localhost and displays any text received

# Check if the script is being run with superuser privileges
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root. Use sudo."
	exit 1
fi

# Start listening on port 98
echo "Listening on localhost:98..."
nc -l -p 98 -s 127.0.0.1
